### ISSUE TITLE
Refactor iterative mle state tomography to use pyquil operator estimation

### ISSUE THREAD

**Issue by mpharrigan** [rigetti/forest-benchmarking#13]
`iterative_mle_state_estimate`'s function signature has been updated to take a list of pyquil's `ExperimentResult`s in place of `TomographyData` in #4. However, under the hood it just shims it into a `TomographyData` and does normal processing. 

The processing needs to be modified to support `ExperimentResult`s directly. This probably involves re-working `_R` to operate on expectation values rather than backing out counts and projectors. [Note that we pull this trick for linear inversion]. In general, this function should be ported to match the style of linear inversion: 

 - operate on ExperimentResults (in any order)
 - return data should just be "new" stuff, like estimate of rho (+ log likelihood?)
 - Use scipy's pinv
 - Remove usage of `construct_projection_operators_on_n_qubits` / `n_qubit_pauli_basis` in favor of `pyquil.unitary_tools.lifted_pauli` and `PauliTerm`s from `ExperimentResult`s.

**Comment by joshcombes** [comment]
On the last point. 

I think we should be careful about relying on the pyQuil unitary tools etc. For many reasons (e.g. the pyQuil re-org) and they don't seem to have informative names unlike `construct_projection_operators_on_n_qubits`. But I agree with the substantive part, i.e  what Matt suggests is a good idea and we should certainly move in that direction.
