### ISSUE TITLE
move partial trace out of utils into operator tools and add tests for calculational.py 

### ISSUE THREAD

**Issue by joshcombes** [rigetti/forest-benchmarking#146]

**Comment by joshcombes** [comment]
partially resolved by https://github.com/rigetti/forest-benchmarking/pull/153/
need to change tests.

**Comment by joshcombes** [comment]
https://github.com/rigetti/forest-benchmarking/pull/163

**Comment by kylegulshen** [comment]
Can't we close this?

**Comment by joshcombes** [comment]
Ahh yes sorry.
