### ISSUE TITLE
CI test fails on occasion due to compiler timeout

### ISSUE THREAD

**Issue by kylegulshen** [rigetti/forest-benchmarking#195]
**Describe the bug**

The compiler times out during CI testing on occasion, e.g. on a call to "quil_to_native_quil". 

**Possible solutions**

Increase the compiler timeout beyond the default.

**Comment by jlapeyre** [comment]
This is the status of one CI "status" for the past 19 hours:
`semaphoreci Expected — Waiting for status to be reported`

Is this related to this issue ? I have not been able to find a way to look at a partial log or status of semaphoreci.

This PR in questions is: https://github.com/rigetti/forest-benchmarking/pull/207
