### ISSUE TITLE
combine `prepare_bitstring` and `_readout_group_bitstring` then put into uilts module

### ISSUE THREAD

**Issue by joshcombes** [rigetti/forest-benchmarking#35]
In the module classical_logic/ripple_carry_adder there is a function called `prepare_bitstring`, it should probably be combined with `_readout_group_bitstring` from the readout module and then put it in utils.

**Comment by kylegulshen** [comment]
Similarly, _readout_group_parameterized_bitstring is currently imported into ripple_carry_adder from readout. This should also be moved to utils, and perhaps renamed to include both preparation and prep+measure use cases.

**Comment by joshcombes** [comment]
redundant with https://github.com/rigetti/forest-benchmarking/issues/96
