### ISSUE TITLE
Remove xData data class definitions where x = Tomography and DFE

### ISSUE THREAD

**Issue by kylegulshen** [rigetti/forest-benchmarking#69]
The pyQuil TomographyExperiment makes the TomographyData and DFEData classes irrelevant. These definitions should be removed, acquire_x_data should simply serve as a wrapper around measure_observables (also with setting qc.compiler.quil_to_native_quil = basic_compile), and the analysis/estimate routines should accept a list of ExperimentResults.

**Comment by kylegulshen** [comment]
@marcusps do you agree with this?

**Comment by marcusps** [comment]
I think we can get away with it for DFE for Cliffords, but probably not for more general DFE (you will need to track weights for each of the terms as well). Other than that, I think the proposal is reasonable, but I'd like to prototype it for DFE first to see if any unanticipated issues come up.

**Comment by marcusps** [comment]
I think we agreed this is not necessary for DFE anymore, @kylegulshen ?

**Comment by kylegulshen** [comment]
Sorry do you mean this issue is no longer necessary?

1) It seems funny to unpack all of the data that comes standard from the return of acquire_data one-to-one into a custom data type with different field names. Even if we keep a DFE_Data I would think it better to simply package a TomographyResult with auxiliary information? 
2) Things might get changed in the data refactor anyway. This is one of the bullets in #84.
3) Can 'tracking weights'  be accomplished by adding coefficients to the out_operators?
