### ISSUE TITLE
Example notebooks should be part of testing

### ISSUE THREAD

**Issue by marcusps** [rigetti/forest-benchmarking#74]
If we don't do this, notebooks will fall out of sync.

**Comment by marcusps** [comment]
@karalekas I remember seeing discussions about how to do this -- I think Johannes and @mpharrigan were the people talking. Do you have any recollection?

**Comment by karalekas** [comment]
There are frameworks to run the NBs I believe, we can look into it.

**Comment by marcusps** [comment]
It may be slow, but perhaps they can be tests we skip by default, but can run when we want to be thorough?

**Comment by karalekas** [comment]
That seems reasonable! We are probably going to have to do some CI optimization anyways, as the build might start taking a while with all these different protocols

**Comment by joshcombes** [comment]
Done here https://github.com/rigetti/forest-benchmarking/pull/123
