### ISSUE TITLE
Forest Benchmarking should depend on PyQuil's operator estimation

### ISSUE THREAD

**Issue by marcusps** [rigetti/forest-benchmarking#86]
No reason to duplicate functionality.

**Comment by marcusps** [comment]
@joshcombes @kylegulshen Thoughts?

**Comment by joshcombes** [comment]
This is a good idea. I'd like to see this happen asap. I'd like the pyQuil `TomographyExperiment` to change to `OperatorExperiment` before we do that. I'll make a pyQuil issue and work with @msohaibalam to get it done.  

Finally, do we know if all the functionality from Nick's code was ported?

**Comment by kylegulshen** [comment]
To clarify, does this mean simply delete operator_estimation.py from forest.benchmarking or do we further need to move some of the functionality from there to pyquil?

**Comment by joshcombes** [comment]
Closed in light of recent internal discussions. The short answer is yes but the how being discussed.
