### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by joshcombes** [rigetti/forest-benchmarking#97]
+ [x] decide if plotting should be in each module or in it's own module (see analysis.fitting.make_figure)
+ [x] ~expand make_figure to include functionality of commented out plotting methods of qubit_spectroscopy and remove those commented sections~
+ [x] move make_figure to plotting (decided against remove plotting and put Hinton in analysis)
+ [x] good state and process matrix plots (**done** https://github.com/rigetti/forest-benchmarking/pull/119)

**Comment by kylegulshen** [comment]
Since make_figure does plot a 'fit' and currently resides in analysis.fitting maybe we can edit one of the init files so that you can import it from either place but the code lives in plotting.
